Restore query parameters on recycle list
owncloud/owncloud-sdk pull request #1002
Opened 2022-02-14 10:15 UTC by diocas

Remove no longer needed dav version option

Looks like if you removed one extra line (and one less) when removing the old dav endpoints.

2022-02-14 10:36 UTC, kulmann requested changes
Hmm, sorry that it got lost. 😞 One nitpick, otherwise of course good to go

2022-02-14 10:36 UTC, kulmann commented on src/filesTrash.js
> +        query: query
```suggestion
        query
```

2022-02-14 10:59 UTC, diocas commented on src/filesTrash.js
> +        query: query
Done

2022-02-14 20:43 UTC, diocas commented
@kulmann can we merge?

2022-02-15 08:27 UTC, kulmann approved these changes
👍

2022-02-15 08:27 UTC, merged

2022-02-15 09:13 UTC, diocas commented
Are you still building the dev versions?

2022-02-15 09:16 UTC, kulmann commented
> Are you still building the dev versions?

No, there is semantic versioning with manual releases now in this repo. I will create one for you.

2022-02-15 09:20 UTC, diocas commented
thanks