Possibility to pass additional context for the search endpoint and _sendDavReport
owncloud/owncloud-sdk pull request #1201
Opened 2023-01-16 14:59 UTC by elizavetaRa

- Enables passing of additional context for search and the used by `_sendDavReport` function.
- In case of path set in the context, passes it to the REPORT request

- Motivation:  CERNBox sdk search can only search inside the given repository (current backend implementation is in addition restricted to certain projects only)

2023-02-03 08:39 UTC, elizavetaRa commented
ping @kulmann @pascalwengerter

2023-02-03 10:28 UTC, kulmann requested changes

2023-02-03 10:28 UTC, kulmann commented on src/fileManagement.js
> +  _sendDavReport (body, plainResult = false, context) {
Please give the `context` a default, i.e. `context = {}`.

2023-02-06 15:21 UTC, kulmann approved these changes
👍

2023-02-06 15:37 UTC, merged