Add notifications features
owncloud/owncloud-sdk pull request #1234
Opened 2023-06-30 11:12 UTC by javfg

Hi ownClouders :wave: 

This PR adds notification features to the SDK, to meet the changes in the [CS3APIs spec regarding notifications](https://cs3org.github.io/cs3apis/#cs3.gateway.v1beta1.AuthenticateRequest#cs3/sharing/link/v1beta1/resources.proto), namely:

* The optional fields `notify_uploads` and `notify_uploads_extra_recipients`.

* A `notify` field to signal the backend to send a notification on a share creation.

It also includes a a `notifyShare` method to `shareManagement` that is used by web to send a notification reminder for a share.

These changes are already being used by the [CERNBox web](https://github.com/cernbox/web/commit/a2be88fa0510c36a63e419df2e08c72b37640992).

2023-07-11 10:43 UTC, JammingBen requested changes
The new code looks good to me. However, please undo the changes you did regarding the versions and the changelog items (except for the new changelog item of course).

After this PR has been merged we can create a new release in https://github.com/owncloud/owncloud-sdk/pull/1192.

2023-07-11 11:13 UTC, javfg commented
> The new code looks good to me. However, please undo the changes you did regarding the versions and the changelog items (except for the new changelog item of course).
> 
> After this PR has been merged we can create a new release in #1192.

Not sure how those 5 commits got in there, I did not upload them. The original PR only included the one that I've just force pushed again now.

Sorry for the confusion, let me know if this is what you meant or I have to fix it some other way!

2023-07-11 11:29 UTC, JammingBen approved these changes
No worries, looks good now 🙂 You just need to rebase your branch with current master to enable the Drone pipeline again.

2023-07-11 13:10 UTC, javfg commented
Done!

2023-07-12 05:57 UTC, merged

2023-07-12 07:30 UTC, JammingBen commented
@javfg I've released `3.1.0-alpha.5` of the sdk which includes your change.

2023-07-12 07:31 UTC, javfg commented
Thanks for the speed @JammingBen! We'll revert the web back to using upstream instead of our fork then.