[Tests-Only] Refactor fileVersionTest to use pact.io
owncloud/owncloud-sdk pull request #601
Opened 2020-10-14 01:41 UTC by HariBhandari07

### Description

2020-10-15 04:26 UTC, individual-it requested changes
something is wrong, the tests fail

2020-10-15 04:26 UTC, individual-it commented on tests/fileVersionTest.js
> +            '    </d:response>\\n' +`
those ticks and quotes look strange
1. the whole return is in enclosed in ticks \` but also in quotes `'`
2. why do we need to have double escaped newlines `\\n` in other places we use only `\n `
3. why do we need the last `+` in line 70?

2020-10-15 08:41 UTC, swoichha requested changes

2020-10-15 08:41 UTC, swoichha commented on tests/fileVersionTest.js
> +    fit('retrieves file versions of not existing file', function (done) {
```suggestion
    it('retrieves file versions of not existing file', function (done) {
```

2020-10-15 08:42 UTC, swoichha commented on tests/fileVersionTest.js
> +            'Access-Control-Allow-Methods': accessControlAllowMethods
We can define this into a constant to make the code DRY as it is repeated in many other places as well.

2020-10-15 09:12 UTC, jasson99 submitted a review, later dismissed

2020-10-15 09:12 UTC, jasson99 commented on tests/fileVersionTest.js
>  // CURRENT TIME
you can remove this as this comment is misleading now

2020-10-16 04:25 UTC, kiranparajuli589 reviewed
LGTM :+1:

2020-10-16 04:26 UTC, individual-it requested changes
please write more explanation about what and why the PR does

2020-10-19 10:03 UTC, individual-it approved these changes

2020-10-19 10:26 UTC, jasson99 reviewed
LGTM

2020-10-19 10:36 UTC, swoichha reviewed
LGTM :+1:

2020-10-19 10:39 UTC, swoichha approved these changes

2020-10-19 10:39 UTC, merged