[Tests-Only] Refactor file test
owncloud/owncloud-sdk pull request #614
Opened 2020-10-23 07:03 UTC by HariBhandari07

2020-11-24 06:37 UTC, swoichha reviewed
LGTM

2020-11-27 05:30 UTC, individual-it requested changes
looks generally good but:
1. write more comments about what you have done in the PR description (comments are love-letters to your future-self)
2. there are still setup and teardown jobs done (e.g. create a folder to test deletion and visa-verse) - we don't need them because we only run the tests on a mock server. make explicit mkdir and explicit delete tests

2020-11-27 05:30 UTC, individual-it commented on tests/filesTest.js
> +        return oc.files.delete(newFolder)
no need to delete the folder after the test, this test is about mkdir and there is no real server running where the folder is created. so this "delete" test should be moved to a separate test, or delete it completely if there are other explicit delete tests (can be done in a separate PR)

2020-11-27 05:30 UTC, individual-it commented on tests/filesTest.js
> +        expect(folder.getName()).toEqual('subdir')
no need to create those folders, they are anyway not created for real

2020-11-27 05:30 UTC, individual-it commented on tests/filesTest.js
> +      })
no need to list those folders afterwards

2020-12-01 10:05 UTC, individual-it approved these changes

2020-12-01 10:42 UTC, merged