[Tests-Only]Test sharing refactor
owncloud/owncloud-sdk pull request #660
Opened 2021-01-08 12:53 UTC by jasson99

## Description:
This PR refactors the sharing test file to use provider verify in the tests.

## Related Issue:
#643

2021-01-12 11:21 UTC, dpakach commented on tests/sharingTest.js
> +          oc = await createOwncloud()
create oc Instance in beforeAll hook

2021-01-13 06:13 UTC, dpakach reviewed
everything looks fine, please squash your commits

2021-01-13 07:00 UTC, individual-it requested changes

2021-01-13 07:00 UTC, individual-it commented on tests/sharingTest.js
> +      it('checking method : getShares for shared file', async function (done) {
no await in this function as far as I see

2021-01-13 08:45 UTC, dpakach commented
@swoichha all looks ok, please fix the commit name

2021-01-13 09:03 UTC, swoichha commented
> @swoichha all looks ok, please fix the commit name

Done

2021-01-13 10:23 UTC, individual-it approved these changes

2021-01-14 08:42 UTC, merged