[Tests-Only] Adjust pact interactions for provider tests for shareRecepient
owncloud/owncloud-sdk pull request #727
Opened 2021-02-11 09:13 UTC by jasson99

## Description:
In this PR, the share recipient test file is adjusted such that the tests pass on the provider side as well.

## Related Issue: 
- https://github.com/owncloud/owncloud-sdk/issues/709

2021-02-15 07:10 UTC, saw-jan commented
LGTM :+1:

2021-02-15 10:41 UTC, individual-it requested changes
just minor comments

2021-02-15 13:07 UTC, jasson99 commented on tests/config/config.drone.json
> +  "testUser2": "testABC",
fixed

2021-02-16 03:28 UTC, individual-it approved these changes

2021-02-16 06:46 UTC, merged