[Tests-Only] SignedUrl integration
owncloud/owncloud-sdk pull request #732
Opened 2021-02-15 13:04 UTC by jasson99

2021-02-17 02:50 UTC, dpakach commented on tests/webdavHelper.js
> +const getSignKey = function (endpoint, username, password) {
```suggestion
const getSignKey = function (username, password) {
```
endpoint is always same

2021-03-01 08:27 UTC, jasson99 commented on tests/webdavHelper.js
> +const getSignKey = function (endpoint, username, password) {
fixed

2021-03-02 03:53 UTC, dpakach reviewed
Lgtm, I dont have much idea about how signed urls work, @individual-it maybe you can review this

2021-03-02 04:56 UTC, individual-it requested changes
good job, but downloading a signed url seems not to work yet
![image](https://user-images.githubusercontent.com/2425577/109599751-d1ee1b00-7b43-11eb-959d-225668b0e09a.png)

2021-03-04 03:29 UTC, individual-it approved these changes

2021-03-04 03:30 UTC, merged