[Tests-Only] adjust pact interactions for unauthorized tests
owncloud/owncloud-sdk pull request #782
Opened 2021-03-16 09:43 UTC by dpakach

related https://github.com/owncloud/owncloud-sdk/issues/780

Adjust pact interaction for unauthorized/filesTest.js

2021-03-16 11:44 UTC, saw-jan reviewed
LGTM :+1:

2021-03-17 05:18 UTC, individual-it approved these changes

2021-03-17 10:55 UTC, saw-jan requested changes
But the tests are still failing in CI. There should be about `66 non-fatal pact failures` but are still `73 non-fatal pact failures`.
```
2.1) has a matching body
--
1766 | $.DAV::error.http://sabredav.org/ns:message.#text
-> Expected 'Username or password was incorrect, Username or password was incorrect, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured'
to be equal to 'Username or password was incorrect, Username or password was incorrect'
```

Also see https://github.com/owncloud/core/issues/38530#issuecomment-800983550

2021-03-18 03:20 UTC, dpakach commented
`Username or password was incorrect, Username or password was incorrect` is still a same messaage repeated twice, In my system I get the longer version for some reason, I'll fix the message to pass on CI

2021-03-18 06:53 UTC, saw-jan approved these changes

2021-03-18 08:00 UTC, merged