[Tests-only] Refactor "filter by tag" test from fileTest.js
owncloud/owncloud-sdk pull request #792
Opened 2021-03-18 11:41 UTC by SwikritiT

This PR 
- refactors `it('checking method: filter by tag'` so that it only tests `getFilesByTags`  and doesn't rely on  `fileInfo`, ` getFileId` `createTag`, ` tagFile` and the respected interactions
- create new tests for `fileInfo`, `createTag`, ` tagFile`

part of : https://github.com/owncloud/owncloud-sdk/issues/789

2021-03-22 03:25 UTC, dpakach reviewed
lgtm :+1:

2021-03-22 10:25 UTC, saw-jan requested changes

2021-03-22 10:25 UTC, saw-jan commented on tests/filesTest.js
> +      await getCurrentUserInformationInteraction(provider)
Can you move these to just after the `createProvider()`
we want to check those interactions before other interactions in a test.
(do similar for other added tests)

2021-03-23 04:45 UTC, saw-jan reviewed
LGTM:+1:

2021-03-23 11:59 UTC, jasson99 reviewed
LGTM

2021-03-24 06:30 UTC, saw-jan approved these changes

2021-03-24 09:20 UTC, individual-it requested changes
looks good, just a small comment

2021-03-24 09:20 UTC, individual-it commented on tests/filesTest.js
> +              dResponse.appendElement('d:href', '', `/remote.php/${data === fileId ? 'webdav' : 'dav/files/' + config.adminUsername}/${testFolder}/${testFile}`)
please make that line shorter

2021-03-25 06:11 UTC, individual-it approved these changes

2021-03-26 10:22 UTC, merged