[Tests-Only] adjust pact interactions for fileTrash and fileVersion tests
owncloud/owncloud-sdk pull request #798
Opened 2021-03-23 07:26 UTC by dpakach

Related - https://github.com/owncloud/owncloud-sdk/issues/780

Fix interaction for pact tests
- [x] - FileTrashTest
- [x] - fileVersionTest

2021-03-23 11:17 UTC, saw-jan commented on tests/fileVersionTest.js
> +            '.*\\/remote\\.php\\/dav\\/meta\\/42\\/v', /* eslint-disable-line no-template-curly-in-string */
`/* eslint-disable-line no-template-curly-in-string */` did you forget to remove?

2021-03-23 11:20 UTC, saw-jan commented on yarn.lock
> +    "@types/pino" "^6.3.5"
Are changes in `yarn.lock` expected to be committed?

2021-03-26 08:50 UTC, saw-jan commented on tests/webdavHelper.js
> +const propfind = function (path, userId, password, properties, type = 'files', folderDepth = '1') {
why `password` and `type` not in doc

2021-03-26 08:50 UTC, saw-jan commented on tests/providerTest.js
> +        // delay(5000)
??

2021-03-26 08:50 UTC, saw-jan commented on tests/webdavHelper.js
> +const getTrashBinElements = function (user, password, depth = 2) {
also include `password` and `depth` in doc

2021-03-26 08:50 UTC, saw-jan commented on tests/fileVersionTest.js
> +        return provider.executeTest(async () => {
```suggestion
        await provider.executeTest(async () => {
```
else the test will only run once

2021-03-26 10:56 UTC, saw-jan commented
LGTM :+1:

2021-03-26 11:18 UTC, individual-it requested changes
please use `createProvider(false, true)` for provider tests that are passing now on oc10

2021-03-26 15:36 UTC, dpakach commented
@individual-it already done that in https://github.com/owncloud/owncloud-sdk/pull/798/files#diff-d4d0ad5a7c6c24e4ff2dd6a7da214b2219a1977b1ef376f315a95c5874d99b16R165
everything else is failing in oc10 as well

2021-03-28 04:06 UTC, individual-it approved these changes

2021-03-28 04:06 UTC, merged