Add more files related test
owncloud/owncloud-sdk pull request #808
Opened 2021-04-12 11:00 UTC by dpakach

Fixes https://github.com/owncloud/owncloud-sdk/issues/756

Add more tests to cover files, trashbin, and favorites scenarios

2021-04-13 03:30 UTC, saw-jan commented on tests/fileTrashTest.js
> +              '/remote.php/dav/trash-bin/' + testUser + '/' + deletedFolderId
yo can also use string literal here

2021-04-13 03:33 UTC, saw-jan commented on tests/fileTrashTest.js
> +      it.only('Trying to restore file should give error', async function () {
```suggestion
      it('Trying to restore file should give error', async function () {
```

2021-04-13 10:53 UTC, saw-jan reviewed
LGTM :+1:

2021-04-15 10:49 UTC, individual-it requested changes

2021-04-15 10:49 UTC, individual-it commented on tests/filesTest.js
> +        .uponReceiving(`as '${username}', a REPORT request to get favorite file when there are not any favorites`)
```suggestion
        .uponReceiving(`as '${username}', a REPORT request to get favorite file when there are no favorites`)
```

2021-04-15 11:54 UTC, individual-it approved these changes

2021-04-15 11:54 UTC, merged